changelog:
  categories:
    - title: "🚀 Nuove Funzionalità (Features)"
      labels:
        - feat
        - feature
    - title: "🐛 Correzioni di Bug (Bug Fixes)"
      labels:
        - fix
        - bug
    - title: "🧹 Pulizia & Rifattorizzazione (Refactoring)"
      labels:
        - refactor
        - chore
  default:
    title: "📝 Altre Modifiche"