changelog:
  exclude:
    labels:
      - ignore
  categories:
    - title: "🚀 Nuove Funzionalità (Features)"
      labels:
        - enhancement
        - feature
      commits:
        types:
          - feat
    - title: "🐛 Correzioni di Bug (Bug Fixes)"
      labels:
        - bug
        - fix
      commits:
        types:
          - fix
    - title: "🧹 Pulizia & Rifattorizzazione (Refactoring)"
      labels:
        - refactor
        - chore
      commits:
        types:
          - refactor
          - chore
  default:
    title: "📝 Altre Modifiche"