--CREATE DATABASE FleetManagement;

CREATE TABLE MODELLI (
    ID_Modello INT PRIMARY KEY IDENTITY,
    Marca VARCHAR(50) NOT NULL,
    NomeModello VARCHAR(50) NOT NULL
);

CREATE TABLE VEICOLI (
    ID_Veicolo INT PRIMARY KEY IDENTITY,
    Targa VARCHAR(10) UNIQUE NOT NULL,
    FK_Modello INT FOREIGN KEY REFERENCES MODELLI(ID_Modello),
    AnnoProduzione INT,
    Chilometraggio INT DEFAULT 0,
    Stato VARCHAR(20) DEFAULT 'Disponibile'
);

CREATE TABLE GUIDATORI (
    ID_Guidatore INT PRIMARY KEY IDENTITY,
    Nome VARCHAR(50) NOT NULL,
    Cognome VARCHAR(50) NOT NULL,
    CodiceFiscale CHAR(16) UNIQUE NOT NULL,
    ScadenzaPatente DATE
);

CREATE TABLE MANUTENZIONI (
    ID_Manutenzione INT PRIMARY KEY IDENTITY,
    FK_Veicolo INT FOREIGN KEY REFERENCES VEICOLI(ID_Veicolo),
    DataIntervento DATE NOT NULL,
    Costo DECIMAL(10,2),
    Descrizione TEXT
);

CREATE TABLE INCIDENTI (
    ID_Incidente INT PRIMARY KEY IDENTITY,
    FK_Veicolo INT FOREIGN KEY REFERENCES VEICOLI(ID_Veicolo),
    FK_Guidatore INT FOREIGN KEY REFERENCES GUIDATORI(ID_Guidatore),
    DataIncidente DATE NOT NULL,
    DescrizioneDanni TEXT
);

CREATE TABLE ASSEGNAZIONI (
    ID_Assegnazione INT PRIMARY KEY IDENTITY,
    FK_Veicolo INT FOREIGN KEY REFERENCES VEICOLI(ID_Veicolo),
    FK_Guidatore INT FOREIGN KEY REFERENCES GUIDATORI(ID_Guidatore),
    DataInizio DATE NOT NULL,
    DataFine DATE NULL
);